# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6943b498214c5cfbdbd0f27e5cf7e320cfb98f804527fb832338fec380ff554b9c67424a63707f0bed4bf2f4d9a2d1301fc09556dd87a08927fe6f943b755d55

test:
  secret_key_base: 86d8ce5b07d761a660107691d209ec5714d9784d588352bc7d294b660d84e3fd6efa1517c4ba3d0c537480cb3fd10ae1aebeedcc49497d6f56e6fe7896d0f00b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
